### ISSUE TITLE
The syntax of this code strikes me as a bit weird：beta: int = 0.1

### ISSUE THREAD

**Issue by chenyv118** [dr-aheydari/SoftAdapt#1]
![image](https://github.com/dr-aheydari/SoftAdapt/assets/92171340/0bfa79db-c678-470b-86b7-756c5d234e18)
Why should the type of beta whose value is a floating point number be int?

**Comment by dr-aheydari** [comment]
Hi @chenyv118,

Thank you for catching that! Yes, that's a typo which should be fixed. However, it should not cause any functional issues, but yes betas should be `float`.

I will try to fix this in the next push. Alternatively, you can do a pull request if you'd like to contribute to the package!

Thanks again!
