### ISSUE TITLE
Wrong types

### ISSUE THREAD

**Issue by EdvardsZ** [dr-aheydari/SoftAdapt#3]
Wrong types.
![image](https://github.com/dr-aheydari/SoftAdapt/assets/52094363/04c0b7a0-b8c3-42db-9b55-1a73c5297cde)

Similar issue to :

https://github.com/dr-aheydari/SoftAdapt/issues/1

In the issue it says it was solved but it appears to me it was not.

**Comment by dr-aheydari** [comment]
Hi @EdvardsZ,

Thank you for catching this issue! Functionally speaking, there should be no arithmetic errors due to this typo, BUT  I will fix the type hint ASAP. 

I will close this issue once I fix the typo! Thank you again for helping me improve SoftAdapt : )

Best wishes,
Ali
